
logLevel = "INFO"

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      certResolver = "default"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

[api]
  dashboard = true
